set(_CATKIN_CURRENT_PACKAGE "waypoint_nav")
set(waypoint_nav_VERSION "0.0.0")
set(waypoint_nav_MAINTAINER "base <base@todo.todo>")
set(waypoint_nav_PACKAGE_FORMAT "2")
set(waypoint_nav_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(waypoint_nav_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(waypoint_nav_BUILDTOOL_DEPENDS "catkin")
set(waypoint_nav_BUILDTOOL_EXPORT_DEPENDS )
set(waypoint_nav_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(waypoint_nav_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(waypoint_nav_TEST_DEPENDS )
set(waypoint_nav_DOC_DEPENDS )
set(waypoint_nav_URL_WEBSITE "")
set(waypoint_nav_URL_BUGTRACKER "")
set(waypoint_nav_URL_REPOSITORY "")
set(waypoint_nav_DEPRECATED "")